#############################################################################
# Makefile for building: FaceRecogtion
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  firstome.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile firstome.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) /usr/local/lib/libopencv_highgui.so /usr/local/lib/libopencv_highgui.so.3.0 /usr/local/lib/libopencv_core.so /usr/local/lib/libopencv_imgproc.so /usr/local/lib/libopencv_imgcodecs.so /usr/local/lib/libopencv_video.so /usr/local/lib/libopencv_shape.so /usr/local/lib/libopencv_videoio.so /usr/local/lib/libopencv_core.so.3.0 /usr/local/lib/libopencv_objdetect.so /usr/local/lib/libopencv_face.so /usr/local/lib/libopencv_face.so.3.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Utils.cpp \
		detectFace.cpp \
		preprocessface.cpp \
		Recongnition.cpp 
OBJECTS       = main.o \
		Utils.o \
		detectFace.o \
		preprocessface.o \
		Recongnition.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		firstome.pro \
		firstome.pro
QMAKE_TARGET  = FaceRecogtion
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = FaceRecogtion


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: firstome.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		firstome.pro
	$(QMAKE) -o Makefile firstome.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
firstome.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile firstome.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/FaceRecogtion1.0.0 || mkdir -p .tmp/FaceRecogtion1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/FaceRecogtion1.0.0/ && (cd `dirname .tmp/FaceRecogtion1.0.0` && $(TAR) FaceRecogtion1.0.0.tar FaceRecogtion1.0.0 && $(COMPRESS) FaceRecogtion1.0.0.tar) && $(MOVE) `dirname .tmp/FaceRecogtion1.0.0`/FaceRecogtion1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/FaceRecogtion1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/face.hpp \
		/usr/local/include/opencv2/face/facerec.hpp \
		Utils.hpp \
		detectFace.hpp \
		preprocessface.hpp \
		Recognition.hpp \
		define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Utils.o: Utils.cpp Utils.hpp \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/ml.hpp \
		detectFace.hpp \
		preprocessface.hpp \
		Recognition.hpp \
		/usr/local/include/opencv2/face.hpp \
		/usr/local/include/opencv2/face/facerec.hpp \
		define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utils.o Utils.cpp

detectFace.o: detectFace.cpp detectFace.hpp \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/ml.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detectFace.o detectFace.cpp

preprocessface.o: preprocessface.cpp preprocessface.hpp \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/ml.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preprocessface.o preprocessface.cpp

Recongnition.o: Recongnition.cpp Recognition.hpp \
		/usr/local/include/opencv2/opencv.hpp \
		/usr/local/include/opencv2/core.hpp \
		/usr/local/include/opencv2/core/cvdef.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/base.hpp \
		/usr/local/include/opencv2/core/cvstd.hpp \
		/usr/local/include/opencv2/core/ptr.inl.hpp \
		/usr/local/include/opencv2/core/traits.hpp \
		/usr/local/include/opencv2/core/matx.hpp \
		/usr/local/include/opencv2/core/types.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/core/bufferpool.hpp \
		/usr/local/include/opencv2/core/mat.inl.hpp \
		/usr/local/include/opencv2/core/persistence.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/include/opencv2/core/utility.hpp \
		/usr/local/include/opencv2/core/optim.hpp \
		/usr/local/include/opencv2/imgproc.hpp \
		/usr/local/include/opencv2/photo.hpp \
		/usr/local/include/opencv2/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/video/background_segm.hpp \
		/usr/local/include/opencv2/features2d.hpp \
		/usr/local/include/opencv2/flann/miniflann.hpp \
		/usr/local/include/opencv2/flann/defines.h \
		/usr/local/include/opencv2/flann/config.h \
		/usr/local/include/opencv2/objdetect.hpp \
		/usr/local/include/opencv2/objdetect/detection_based_tracker.hpp \
		/usr/local/include/opencv2/calib3d.hpp \
		/usr/local/include/opencv2/core/affine.hpp \
		/usr/local/include/opencv2/imgcodecs.hpp \
		/usr/local/include/opencv2/videoio.hpp \
		/usr/local/include/opencv2/highgui.hpp \
		/usr/local/include/opencv2/ml.hpp \
		/usr/local/include/opencv2/face.hpp \
		/usr/local/include/opencv2/face/facerec.hpp \
		define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Recongnition.o Recongnition.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

